name: waffles_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda-forge::root
  - pip
  - pip:
    - sphinx==5.0
    - alabaster==0.7.13
    - graphviz
    - lxml==4.9.1
    - myst_parser
    - myst_nb
    - nbsphinx
    - requests-futures==1.0.0
    - sphinxemoji
    - sphinx_book_theme
    - sphinx_copybutton
    - sphinx_plotly_directive
    - sphinx_rtd_theme==0.5.0rc1
    - awkward
    - inquirer
    - ipywidgets
    - matplotlib
    - numba
    - numba_stats
    - pandas
    - numpy
    - plotly
    - rich
    - scipy 
    - uproot
    - click
    - dash
    - dash_bootstrap_components
    - jupyter
    - kaleido
    - .