# ------- General parameters -------

#I added this
baseline_method: EasyMedian

# Path to the folder containing the data
input_path: "/eos/experiment/neutplatform/protodune/experiments/ProtoDUNE-VD/commissioning/processed/run037268_cathode/processed_merged_run037268_structured_cathode.hdf5"

# Path to the output
output_path: "output/"

# Runs
runs: [37268]

# Detector to analyze: Membrane, Cathode, PMTs
det: "Cathode"

# 1 is non-TCO and 2 is TCO
det_id: [2]

# ------- Parameters for the analysis -------

# Analysis label
analysis_label: 'standard'

# Time interval in timeticks of the DAQ window to be considered 
tmin: -1000
tmax: 1000

# Channels 
ch: -1

# Number of waveforms to analyze
nwfs: -1

# Number of waveforms to plot
nwfs_plot: -1

# Records
rec: [-1]

# Integration limits
starting_tick: 60

# Baseline limits
baseline_limits:
    - 0
    - 100
    - 900
    - 1000

# Integration window width, in time ticks
integ_window: 60

# Number of bins for the histograms 
nbins: 110




