# ---------------------------------------------------------------------
# --- ANALYSIS 1 PARAMETERS -------------------------------------------
# ---------------------------------------------------------------------
# not used in the analysis
input_path: "data"
output_path: "output"

# Do you want to use full statistics? (True/False)
full_stat: False

# Debug mode? (True/False)
debug_mode: True

# Append or overwrite the output files? (append="a", overwrite="w")
out_writing_mode: "w"

# Which runs are you interested in? (e.g. [31920, 31928])
# Leave it empty if you want to use all the runs []
user_runs: []
# user_runs: [31940]
#
# Where do you want to save the output files? (e.g. "/eos/YOUR_PATH/Noise_Studies/analysis/")
out_path: "./"
# out_path: "/eos/home-f/fegalizz/ProtoDUNE_HD/Noise_Studies/analysis/"

# ---------------------------------------------------------------------
# --- ANALYSIS 2 PARAMETERS -------------------------------------------
# ---------------------------------------------------------------------
# Dictionary of daphne AFEs and the vgain set
# Remember ch [10400->10407] are in Endpoint 104 and AFE 0
# here we call it AFE 1040
# At the bottom a template with the AFEs used for most of the runs
daphneAFE_vgain_dict:
  1040: 2318
  1041: 2318
  1050: 2318
  1051: 2318
  1052: 2318
  1070: 2318
  1071: 2318
  1090: 2318
  1091: 2318
  1092: 2318
  1093: 2318
  1094: 2318
  1110: 2318
  1111: 2318
  1112: 2318
  1113: 2318
  1114: 2318
  1120: 2318
  1121: 2318
  1122: 2318
  1123: 2318
  1124: 2318
  1130: 2318

# Template for the daphneAFE_vgain_dict
daphneAFE_vgain_dict_TEMPLATED:
  1040: 2318
  1041: 2318
  1050: 2318
  1051: 2318
  1052: 2318
  1070: 2318
  1071: 2318
  1090: 2318
  1091: 2318
  1092: 2318
  1093: 2318
  1094: 2318
  1110: 2318
  1111: 2318
  1112: 2318
  1113: 2318
  1114: 2318
  1120: 2318
  1121: 2318
  1122: 2318
  1123: 2318
  1124: 2318
  1130: 2318
