
# ------- General parameters -------

# APA number
apas: [2,3,4] # 1, 2, 3, 4

# Photon detection efficiency
pdes: [0.4,0.45] # 0.40, 0.45, 0.50

# Calibration-batch number
batches: [3] # 1, ...

# Path to the folder containing the data
input_path: 'data'

# Path to the output
output_path: 'output'

# PDE-to-OV mapping for HPK sipms
hpk_ov:
    0.4: 2.0
    0.45: 3.5
    0.50: 4.0

# PDE-to-OV mapping for FBK sipms
fbk_ov:
    0.4: 3.5
    0.45: 4.5
    0.50 : 7.0

# Enumeration of PDE values
ov_no:
    0.4: 1
    0.45: 2
    0.50: 3

# ------- Parameters for charge histogram -------

analysis_label: 'standard'

# Lower integration limits. For APA 1 the limits are
# run-wise, while for APA 2, 3, 4 they are the same
# for all runs 
starting_tick:
    1:
        27818: 621
        27820: 615
        27822: 615
        27823: 615
        27824: 615
        27825: 615
        27826: 615
        27827: 632
        27828: 626
        27898: 635
        27899: 635
        27900: 618
        27921: 602
        27901: 615
        27902: 615
        27903: 615
        27904: 630
        27905: 620
        27906: 610
        27907: 608
        27908: 602
    2:
        125
    3:
        125
    4:
        125

# Baseline limits
baseline_limits:
    1:
        - 100
        - 400
    2: 
        - 0
        - 100
        - 900
        - 1000
    3: 
        - 0
        - 100
        - 900
        - 1000
    4: 
        - 0
        - 100
        - 900
        - 1000

# Integration window width, in time ticks
integ_window: 40

# ------- Parameters for peak fitting -------

# Maximum number of peaks to fit
max_peaks: 2

# Minimal prominence, as a fraction
# of the y-range, for a peak to be detected
prominence: 0.15 # [0.10 - 0.2]

# The number of points to fit on either side
# of the peak maximum. P.e. setting this to 
# 2 will fit 5 points in total: the maximum
# and 2 points on either side
half_points_to_fit: 2 # [2 - 3] 

# Check the documentation of the
# 'initial_percentage' and 'percentage_step'
# parameters of the
# __spot_first_peaks_in_CalibrationHistogram
# function defined in 
# utils/fit_peaks/fit_peaks_utils.py
initial_percentage: 0.15 
percentage_step: 0.05