
# ------- General parameters -------

# Path to the folder containing the data
input_path: 'data'

# Path to the output
output_path: 'output'

# Calibration-batch number
batches: [1, 2, 3, 4, 5, 6, 7] # 1, ..., 7

# APA number
apas: [1, 2, 3, 4] # 1, 2, 3, 4

# Photon detection efficiency
pdes: [0.4, 0.45, 0.5] # 0.40, 0.45, 0.50

# Path to a CSV file which lists the channels
# which should be calibrated for each run
channels_per_run_filepath: './configs/channels_per_run_database.csv'

# Path to a CSV file which lists the channels
# which should be excluded from the calibration
excluded_channels_filepath: './configs/excluded_channels_database.csv'

# Whether to show the produced figures
show_figures: false

# Whether to print verbose messages
verbose: true

## Parameters for the baseline analysis
baseline_analysis_label: 'baseliner'
null_baseline_analysis_label: 'null_baseliner'

baseline_limits:
    1:
        - 0
        - 100
        - 900
        - 1000
    2: 
        - 0
        - 100
        - 900
        - 1000
    3: 
        - 0
        - 100
        - 900
        - 1000
    4: 
        - 0
        - 100
        - 900
        - 1000

baseliner_std_cut: 3.
baseliner_type: 'mean'

## Parameters for the coarse selection cut
lower_limit_wrt_baseline: -200.
upper_limit_wrt_baseline: 40.

## Parameters for the fine selection cut
baseline_i_up:
    1:
        575
    2:
        120
    3:
        120
    4:
        120
signal_i_up:
    1:
        650
    2:
        165
    3:
        165
    4:
        165

baseline_allowed_dev: 4.
signal_allowed_dev: 10.

## Parameters for the computation of the integration window
deviation_from_baseline: 0.3
lower_limit_correction: 0
upper_limit_correction: 0

## Parameters for the integration analysis
integration_analysis_label: 'integrator'

## Parameters for the calibration histogram
# Used if gain_seeds_filepath is None
# Bins width in the calibration histogram for each PDE
calib_histo_bin_width:
    0.4:
        480.
    0.45:
        571.
    0.50:
        667.

# Used if gain_seeds_filepath is None
# Lower and upper limits for the calibration histogram
calib_histo_lower_limit: -10000.
calib_histo_upper_limit: 50000.

# If None, the number of bins and the domain of the charge
# calibration histogram are computed out of the
# calib_histo_bin_width, calib_histo_lower_limit and
# calib_histo_upper_limit input parameters. If it is defined,
# then it should give the path to a CSV file which contains,
# at least, the following columns: 'batch', 'APA', 'PDE',
# 'endpoint', 'channel' and 'gain'. The channel-wise gain
# read from such file is used to compute a channel-wise number
# of bins and domain for the charge calibration histograms.
gain_seeds_filepath: './configs/gain_seeds.csv'

# Used only if the gain_seeds_filepath parameter is defined.
# In that case, the calibration histogram (CH) domain is
# automatically set to [-1.*gain_seed, 5.*gain_seed], and
# the number of bins in the CH is computed as the domain 
# width (i.e. 6.*gain_seed) multiplied by this parameter.
bins_per_charge_peak: 7

# Used only if the gain_seeds_filepath parameter
# is defined. In that case, and if the given CSV lacks the
# gain-seed information for one or more of the required
# channels, then the domain (for the calibration histogram)
# for the lacking channels is set to the average domain of
# all of the other channels.
average_fallback: true

## Parameters for peak fitting
# Maximum number of peaks to fit
max_peaks: 2

# Minimal prominence, as a fraction
# of the y-range, for a peak to be detected
prominence: 0.15 # [0.10 - 0.2]

# These parameters have to do with the peak
# detection in the calibration histogram. For
# more information check the documentation of
# the 'initial_percentage' and 'percentage_step'
# parameters of the
# __spot_first_peaks_in_CalibrationHistogram
# function defined in 
# utils/fit_peaks/fit_peaks_utils.py
initial_percentage: 0.15
percentage_step: 0.05

# It can be either 'correlated_gaussians'
# or 'independent_gaussians'
fit_type: 'correlated_gaussians'

# Only used if fit_type is set to 'independent_gaussians'.
# The number of points to fit on either side
# of the peak maximum. P.e. setting this to 
# 2 will fit 5 points in total: the maximum
# and 2 points on either side.
half_points_to_fit: 2 # [2 - 3] 

# Only used if fit_type is set to 'correlated_gaussians'.
# It is used when the peak finder predicts that the
# standard deviation of the second peak is less than
# the standard deviation of the first peak, which is
# incompatible with our fitting function. In this case,
# the seed for the standard deviation increment is set
# to this value.
std_increment_seed_fallback: 100.

# Only used if fit_type is set to 'correlated_gaussians'.
# It determines the limits of the subrange of the
# calibration histogram which is considered for the fit.
# The lower (resp. upper) limit is computed as the
# maximum of the first (resp. last) peak position minus
# (resp. plus) this fraction of the full range of the
# calibration histogram. For 50% (resp. 40%) PDE, this value
# should not be greater than 0.05 (resp. 0.04).
ch_span_fraction_around_peaks: 0.03

# Whether to save the persistence heatmaps of the
# integrated waveforms or not
save_persistence_heatmaps: true

output_dataframe_filename: 'calibration_results.csv'