# File.csv containing (at least) the columns:
# Run, Threshold, LED
# Run: run number
# Threshold: threshold in exadecimal
# LED: LED intensity
run_info_file: "./configs/SelfTrigger_RunInfo.csv"

# Where to store the output files
ana_folder: "/eos/home-f/fegalizz/ProtoDUNE_HD/SelfTrigger/analysis/"

# File.csv stored in ana_folder containing (at least) the columns:
# SiPMChannel, IntLow, IntUp, PrepulseTicks, BaselineRMS, SpeCharge, SNR, SpeAmpl
# SiPMChannel: SiPM channel number (e.g. 11121)
# IntLow: lower integration limit (in ticks)
# IntUp: upper integration limit (in ticks)
# PrepulseTicks: number of ticks before the signal to compute the baseline
# BaselineRMS: baseline RMS (in ADC counts)
# SpeCharge: SPE charge (in ADC x ticks)
# SpeAmpl: SPE amplitude (in ADC counts)
calibration_file: "SelfTrigger_Calibration.csv"

# Path to the hdf5 files with name:
# Run_XXXXXX_ChSiPM_YYYYY_ChST_ZZZZZ_structured.hdf5 
file_folder: "/eos/home-f/fegalizz/ProtoDUNE_HD/SelfTrigger/files/"

# SiPM channel to analyze
SiPM_channel: 11121

# Do you want to save all the png of the Total/Passed histograms?
save_pngs: False

# List of runs to analyze
runs : []
