input_path: ""
output_path: "output/"

runs:
  - 30201


waveforms_per_run: 500
correct_by_baseline: True
rucio_paths_directory: "/eos/experiment/neutplatform/protodune/experiments/ProtoDUNE-II/PDS_Commissioning/waffles/1_rucio_paths"