# Runs to be analyzed
runs : [30666]

# File.csv with an OfflineCh <-> RMS mapping for a given
# VGain and Integrators ON/OFF configuration
noise_results_file : "/eos/home-f/fegalizz/ProtoDUNE_HD/Noise_Studies/analysis/FFT_sets/OfflineCh_RMS_Config_31.csv"

# File.csv with the calibration results 
calibration_file : "/eos/home-f/fegalizz/ProtoDUNE_HD/TimeResolution/analysis/TimeResolutionCalib_golden_runs.csv"

# If empty, all the calibrated channels will be analyzed
channels  : []

prepulse_ticks : 125
int_low : 130
int_up : 155
postpulse_ticks : 155

min_pes : 5

methods : ["amplitude", "integral", "denoise"]

relative_thrs : [0.5]

filt_levels : [8, 12]

h2_nbins  : 100
stat_lost : 0.005
